### ISSUE TITLE
Piwik minimum version

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/Piwik-IntranetGeoIP#10]
@tsteur I've updated my plugin to the new Piwik\Network\IP instead of the old Piwik\IP and published a new release.
I've updated the Piwik requirement as well to the minimum PIwik version needed for this.
https://github.com/ThaDafinser/IntranetGeoIP/blob/master/plugin.json

People who already have this plugin: Can it happen that they get the new release over a plugin update,  although it wont work?

**Comment by tsteur** [comment]
Nope, they shouldn't get the update. They will see an information that they need to upgrade in order to install it.

**Comment by ThaDafinser** [comment]
Thank you!
