### ISSUE TITLE
Any particular Location Provider necessary?

### ISSUE THREAD

**Issue by junctionapps** [ThaDafinser/Piwik-IntranetGeoIP#13]
I've installed and activated IntranetGeoIP, configured the the IntranetGeoIP.data.php file correctly I believe (attempting to match 10.10.55.20 with 
 'networks' => [
            '10.10.0.0/16'
        ]
but not seeing the results I'm expecting; still getting 'unknown' instead of what I put in VisitorInfo. 

I was using the default Location Provider in the GeoLocation settings, then switched to GeoIP (PHP), then GeoIP (Apache) and GeoIP (PECL) thinking that maybe one of those was necessary; each with the same result. I don't need to match anything outside of the intranet's ranges.

noMatch is not commented out, and I'm not getting the string I've placed there for for 'location_provider'. 

I feel like the plugin is being ignored, even though activated. Clearly, I've missed something, but wondering if you happen to be able to tell me from the description above.

**Comment by junctionapps** [comment]
didn't realize there were some closed issues. I see there is no such requirement for location provider. I must have a mismatch somewhere.

**Comment by junctionapps** [comment]
I had incorrectly escaped a city's name which had an apostrophe. What would be the appropriate way to escape that?
'location_city' => 'Saint John''s',   //did not work

**Comment by ThaDafinser** [comment]
@junctionapps it's just a PHP array.

```php
return array(
    // good
    'location_city' => 'Saint John\'s',

    // or
    'location_city' => "Saint John's",
);

**Comment by junctionapps** [comment]
Perfect; thank you. Went with the \'
Creating a segment in Piwik like "City Is Saint John's" is another issue (I've posted on Piwik forums). The quote is replaced with a right parenthesis after 'Save & Apply'.

**Comment by ThaDafinser** [comment]
Good to hear :+1:
