### ISSUE TITLE
piwik intranetgeoip and multiple networks / locations

### ISSUE THREAD

**Issue by Gyurltrini** [ThaDafinser/Piwik-IntranetGeoIP#15]
Hi,
So I've been trying to use piwik on an intranet / extranet mixed environment (with multiple networks and physical locations) using your plugin. However, there are a couple of things I'm noticing:
1. there are a number of "Provider: Unknown" and location unknown, although I put all of the locations and providers & ip address ranges into the script (my feeling is with so many blocks of known visitors, perhaps the script's getting confused?)
2. Although the country is set properly in the script (for known visitors), etc., especially with the "Provider: Unknown" logs, it is sometimes gives the wrong country name
3. Sometimes it's the gateway's ip address (there are multiple gateways between the different networks / locations on our environment) that's used instead of the actual ip address of the computer. I don't know if that has anything to do with your plugin or piwik itself, but that's what I've noticed.

Piwik version: 2.14.3
intranetGeoIP version: 2.2.0 
If you have any suggestions on how to resolve any of these issues, I would greatly appreciate it.

Update: I added the country to the unmatched address block, however, after double checking I'm realising that the Unknown Provider ip addresses are definitely included in the ip ranges of the known visitor blocks, but, somehow it isn't being detected, or they're being overruled.

I'm asking about this because I've got to try to segment the visitors by physical location & there are multiple locations in this case.

**Comment by ThaDafinser** [comment]
> 1. there are a number of "Provider: Unknown" and location unknown, although I put all of the locations and providers & ip address ranges into the script (my feeling is with so many blocks of known visitors, perhaps the script's getting confused?)

Please double check the logged IP address with your ranges. Are they really inside the range?

> 2. Although the country is set properly in the script (for known visitors), etc., especially with the "Provider: Unknown" logs, it is sometimes gives the wrong country name

This is default piwik behaviour. Please check the setting `enable_language_to_country_guess`

> 3. Sometimes it's the gateway's ip address (there are multiple gateways between the different networks / locations on our environment) that's used instead of the actual ip address of the computer. I don't know if that has anything to do with your plugin or piwik itself, but that's what I've noticed.

I think this is not a problem of the plugin. Please check what IP address is logged in Piwik, if it's the gateway, maybe you need to make some configurations somewhere...but i don't know that tbh.

**Comment by ThaDafinser** [comment]
no feedback. Closing as question.
