### ISSUE TITLE
Local Connections not showing on real-time map

### ISSUE THREAD

**Issue by plegault3397** [ThaDafinser/Piwik-IntranetGeoIP#22]
I have a very large network, and I'm adding a lot of address blocks and not seeing any connections on the real-time map

Is there something else I need to do to get it to work other than activate it?
Under Geolocation I have GeoIP (PHP) Selected

I stopped seeing traffic altogether

**Comment by ThaDafinser** [comment]
> I stopped seeing traffic altogether

That sounds like a general error. 

Can you check your error log?
http://piwik.org/faq/troubleshooting/faq_115/

**Comment by plegault3397** [comment]
I enabled the logging and I get an error log file does not exist
I create a log file and I do not get any errors

**Comment by plegault3397** [comment]
You are currently using Piwik 2.16.2-b1.

**Comment by plegault2** [comment]
After revisiting this I was bale to fix it
