### ISSUE TITLE
Update plugin.json required version

### ISSUE THREAD

**Issue by tsteur** [ThaDafinser/Piwik-IntranetGeoIP#24]
Hi there,

I'm Thomas from Piwik. We recently made some changes on the Marketplace and changed how versions are defined. In your plugin.json it defines:

```json
  "require": {
    "piwik": "2.9.0",
    "php": "5.4.0"
  }
```

but in future updates it should include the `>=` and also include an upper version constraint:

```json
  "require": {
    "piwik": ">=2.9.0,<3.0.0-b1",
    "php": ">=5.4.0"
  }
```

Sorry for inconvenience and cheers

**Comment by ThaDafinser** [comment]
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases/tag/v2.3.0
