### ISSUE TITLE
Plugin Update not working

### ISSUE THREAD

**Issue by sgreiner** [ThaDafinser/Piwik-IntranetGeoIP#25]
Hi,

I have the following installation: Piwik 2.16.2 + IntranetGeoIP Version 2.1.3

In the Plugin-Admin-Page Piwik wants me to update from 2.1.3 => 2.2.0
After updating the Plugin, Piwik is Broken. I looked into the files (plugin.json) and now there is 1.0.2 installed.

If I download the 2.2.0 Plugin-Version from Github it wants me to update 2.2.0 => 2.2.0

If I go with the Web-Browser to: https://plugins.piwik.org/search?piwikversion=0&query=intranetGeo I get the 2.1.3 Version.

I have also seen, that the Plugin Version on GitHub Tag v2.3.0 does not match the version in its plugin.json (there it says 2.2.0)

Something is not working here...

**Comment by ThaDafinser** [comment]
@sgreiner i created a new tag with the proper version.

Can you try the update again?
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases

**Comment by sgreiner** [comment]
The Version is indeed fixed now in the plugin.json in your tag 2.3.1

But the Version I got from Piwik Marketplace is still 1.0.2
This Broke my installation again.

I downloaded the tag 2.3.1 from github now and installed it manually.
Piwik now wants me to update Plugin from version 2.3.1 => 2.3.1

So the Plugin from the Marketplace is still broken as before.

**Comment by ThaDafinser** [comment]
okay we seem to be close to an solution...

I created now a new release without the "v" as prefix https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases/tag/2.3.1

Can you try the update a last time? If that works i will update my other plugins as well.

**Comment by ThaDafinser** [comment]
There is also a newer tag with 2.3.2 to reflect the changes to the marketplace

**Comment by ThaDafinser** [comment]
Just released the package for piwik3- should be soon available over the marketplace!
