### ISSUE TITLE
Plugin broke

### ISSUE THREAD

**Issue by phoob** [ThaDafinser/Piwik-IntranetGeoIP#26]
Hello!

I got an upgrade notice a few days ago, and I think that broke the plugin. I see that IntranetGeoIp.php now references a function called "IP::isIpInRange", which doesn't exist in \Piwik\IP… Actually I think maybe the plugin hasn't been updated for a while – because until now I had the local IP definitions in config/IntranetGeoIP.data.php – and that worked until the plugin got updated just now.. Actually I can't see the isIpInRange function in /component-network/blob/master/src/IP.php either… but that doesnt seem to be included in the piwik installation anyway..

**Comment by ThaDafinser** [comment]
@phoob which piwik/php version you use and which IntranetGeoIp?

**Comment by ThaDafinser** [comment]
Function is still here - but moved the namespace.

This module should work with the lastes 2.16 release.

 https://github.com/piwik/piwik/blob/77a6412ff7a8bdb2f23fb00a2d8ce22e7a35fcee/CHANGELOG.md#piwik-2120

https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L8
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L120

**Comment by phoob** [comment]
Will check more later tonight.. but have you checked the package that is downloaded from the piwik marketplace.. that it is the correct version? Didnt look like the one in master here.. but maybe it was only a glitch?






On Thu, Sep 1, 2016 at 4:15 PM +0200, "Martin Keckeis" <notifications@github.com> wrote:












Function is still here - but moved the namespace.



This module should work with the lastes 2.16 release.



https://github.com/piwik/piwik/blob/77a6412ff7a8bdb2f23fb00a2d8ce22e7a35fcee/CHANGELOG.md#piwik-2120



https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L8

https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L120

**Comment by phoob** [comment]
Nope… When updating the plugin, I get version 1.0.2...

**Comment by ThaDafinser** [comment]
@phoob please tell me which PHP/Piwik version do you use.

**Comment by phoob** [comment]
Piwik 2.16.2, mariadb 10.1.17

**Comment by ThaDafinser** [comment]
@phoob i still need the PHP version :-)
Maybe this is the issue, that the newest update does not work

**Comment by phoob** [comment]
Sorry, php7

**Comment by ThaDafinser** [comment]
Okay - then all requirements for the latest version should be met :-/

> Nope… When updating the plugin, I get version 1.0.2...
I think this is the an old problem when i deleted this release here, but the marketplace keeps the version (there is no 1.0.2 on github anymore)
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases
http://plugins.piwik.org/IntranetGeoIP

@tsteur it seems that once you "f***ed" the versioning up you cannot clean the old changelog/version history on the marketplace as well
https://github.com/piwik/piwik/issues/5921#issuecomment-244176838


Can you do a manual upgrade to the latest release? I will try to investigate the problem.
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases/tag/2.3.2

**Comment by tsteur** [comment]
@ThaDafinser As soon as a version is released the marketplace checks out that tag and creates a zip for it. It is indeed not possible to delete that version afterwards currently. The only way is to release a new version with a different version number. When I download the zip from the Marketplace it seems to show the latest version for 2.3.2. The ZIP seems to have the latest version as well. When I check in Piwik it offers me version 2.3.2 as well.

**Comment by tsteur** [comment]
@phoob in the Piwik Admin as a super user can you click on "check for updates" and then have a look which version it shows for that plugin? cheers

**Comment by phoob** [comment]
after having manually uploaded the latest release that I downloaded from GitHub, and doing what you say, it says version 2.3.2. I also tried re-installing the plugin from the admin, and now that seems to work as well. But I do get some weird upgrade notices, like this:

![skjermbilde 2016-09-02 kl 10 33 59](https://cloud.githubusercontent.com/assets/1475800/18197820/8fab43ca-70f9-11e6-943f-6011abcd73cd.png)

![skjermbilde 2016-09-02 kl 10 40 06](https://cloud.githubusercontent.com/assets/1475800/18197827/a47eba66-70f9-11e6-951a-366a4a812542.png)

**Comment by phoob** [comment]
I checked which versions of PerformanceInfo I actually had installed, and it is v0.2.1. Both before and after the update..

**Comment by ThaDafinser** [comment]
@phoob this is another plugin. 
I want to make sure this plugin works correctly now with the versions/tags i created. After that i create new releases there.

**Comment by tsteur** [comment]
@phoob re the other plugin this might be actually a bug on the Marketplace. I'll have a look at this tmrw. Cheers

**Comment by tsteur** [comment]
I know it is a bit off topic here but do you mind clicking on "check for updates" again the admin and then check if it still offers you to update 0.2.2 => 0.2.2 @phoob

**Comment by ThaDafinser** [comment]
@phoob did it work? If yes, i can change the other plugins as well...

**Comment by phoob** [comment]
Hello! The plugin works now, the only thing was that the file with custom ip ranges I had created was deleted... Luckily I had a backup :) Also, the nagging about outdated plugins which aren't really outdated has gone away for now.

**Comment by ThaDafinser** [comment]
The plugin itself do remove it, if you remove the plugin (proper cleanup)
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/blob/master/IntranetGeoIP.php#L79-L87

Then i will create now new releases for the other plugins. Thank you!
