### ISSUE TITLE
Question about requirements (PHP7)

### ISSUE THREAD

**Issue by peterbo** [ThaDafinser/Piwik-IntranetGeoIP#33]
Hi @ThaDafinser, I can remember a discussion why it was necessary to raise the requirements of the plugin to PHP7 (something about different variable/pointer handling I guess). Now I'm struggling with an instance running PHP5.6 and Piwik3, unable yet to upgrade to PHP7. Therefore I would like to backport the Plugin for the instance to work on PHP5.6, if possible. Could you please point me to the direction, what exactly was not working as expected on PHP < 7?

Thank you in advance!

**Comment by ThaDafinser** [comment]
@peterbo AFAIK i didn't used php7 features in the plugin, so you should be able to download the zip and change the requirements - it should still work.

More informations you can find here
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/issues/10#issuecomment-286109983

**Comment by peterbo** [comment]
Hi @ThaDafinser, thanks for the info and the fast response. It would be nice if plugins would be mostly in line with the requirements of Piwik itself, because it is near impossible to check the requirements of every single plugin before updating many instances. Requirements should only be raised if it's really needed by basic plugin functionality. No rant, just my 50 cents!

Nevertheless, thank you for the plugin and fast reponse!
Peter
